import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { rootDirectory } from './runtime.mjs';

// One Nx task graph shares declared build prerequisites across all current lanes.
const commands = [
  [process.execPath, ['scripts/check-workspace.mjs']],
  // Check committed generated bytes before Vite has an opportunity to rewrite them.
  [process.execPath, ['--test', 'scripts/route-generation.test.mjs']],
  [
    process.execPath,
    [
      path.join(rootDirectory, 'node_modules/eslint/bin/eslint.js'),
      'apps/pharo-dashboard-ui',
      'packages',
      'scripts',
      '*.mjs',
    ],
  ],
  [
    process.execPath,
    [
      'scripts/nx.mjs',
      'run-many',
      '-t',
      'typecheck,typecheck:catalog,format,test,build,infrastructure,e2e',
      '-p',
      'pharo-dashboard-ui,pharo-dashboard-api,@pharo/eslint-config,@pharo/prettier-config,@pharo/react-components,@pharo/react-form-components,@pharo/react-charts,@pharo/tailwind-plugin',
    ],
  ],
];

for (const [command, args] of commands) {
  const result = spawnSync(command, args, { stdio: 'inherit' });

  if (result.error) console.error(result.error.message);
  if (result.status !== 0) process.exit(result.status ?? 1);
}
